### PR TITLE
Adding a container fetcher

### PR DESCRIPTION
**Pull request by lightshire**
Thanks for contributing. Please check the following points before submitting your pull request. Thank you!

- [x ] I have read and followed the contribution guide: https://github.com/pagekit/pagekit/blob/develop/.github/CONTRIBUTING.md
- [x ] The destination branch of the pull request is the `develop` branch
Need this for extending and adding console commands

### CODE REVIEW

**Comment by MalteScharenberg** [comment]
The container is a property of every command (https://github.com/pagekit/pagekit/blob/develop/app/modules/application/src/Application/Console/Command.php#L44). You can access it via `$this->container` within a command. Dose this help you?

**Comment by lightshire** [comment]
No,

I won't access it via the command but from

```php
<?php
return [
    'events' => [
         'console.init' => function ($event, $console) {
              //I have to get it here
               SomeClassIHave::boot($console->getContainer());
          }
    ]
];
```

**Comment by crwgregory** [comment]
I'm a little late to the party and don't know if this is already further explanation to the reason for this in an issue somewhere that I haven't read... But why do you need this? The container set on the Console constructor is just the Pagekit\Application, you should have direct access to it with `App::getInstance();`.

**Comment by lightshire** [comment]
@crwgregory didn't know we had that.

got it working.

**Comment by MalteScharenberg** [comment]
Or just:

```php
<?php
return [
    'events' => [
         'console.init' => function ($event, $console) use ($app) {
               SomeClassIHave::boot($app);
          }
    ]
];
```

**Comment by lightshire** [comment]
@MalteScharenberg uhuh, didn't know we could do that. Got it!

Thanks

**Pull request closed without merging**
