### PR TITLE
Update apache mod_rewrite engine check at index.php

### PR DESCRIPTION
**Pull request by lapaygroup**
Thanks for contributing. Please check the following points before submitting your pull request. Thank you!

- [x] I have read and followed the contribution guide: https://github.com/pagekit/pagekit/blob/develop/.github/CONTRIBUTING.md
- [x] The destination branch of the pull request is the `develop` branch

### CODE REVIEW

**Comment by MalteScharenberg** [comment]
It would be great if you could shine some light on what the issue was. :) 
Are there situations where 'HTTP_MOD_REWRITE' is false but 'REDIRECT_HTTP_MOD_REWRITE' is true?

**Comment by lapaygroup** [comment]
ISP Manager System 5  when you turn on mod_rewrite in Apache 2.4 somehow does not pass the parameter 'HTTP_MOD_REWRITE' in $ _SERVER but there is a parameter 'REDIRECT_HTTP_MOD_REWRITE'. Having learned about similar problems on the forums decided it in this way. 

Example $_SERVER on my server:
Array
(
    [REDIRECT_HTTP_MOD_REWRITE] => On
    [REDIRECT_HANDLER] => application/x-httpd-php5
    [REDIRECT_STATUS] => 200
    [HTTP_HOST] => pagekit.tech
    [HTTP_CONNECTION] => keep-alive
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, sdch
    [HTTP_ACCEPT_LANGUAGE] => ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
    [HTTP_COOKIE] => pagekit_session=f935srpj80davn2d4c5l34mj35; pagekit_auth=utQ7qUv0bQOBUhT0YFY.iX0l6eXVhm4CApRwunAMEavKGV%2FpONWz05euGnOB31Ma
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [SERVER_SIGNATURE] => Apache/2.4.10 (Debian) Server at pagekit.tech Port 80
    [SERVER_SOFTWARE] => Apache/2.4.10 (Debian)
    [SERVER_NAME] => pagekit.tech
    [SERVER_ADDR] => 138.201.51.117
    [SERVER_PORT] => 80
    [REMOTE_ADDR] => 176.193.215.84
    [DOCUMENT_ROOT] => /var/www/pagekit/data/www/pagekit.tech
    [REQUEST_SCHEME] => http
    [CONTEXT_PREFIX] => /php-bin/
    [CONTEXT_DOCUMENT_ROOT] => /var/www/php-bin-isp-php70/pagekit/
    [SERVER_ADMIN] => webmaster@pagekit.tech
    [SCRIPT_FILENAME] => /var/www/pagekit/data/www/pagekit.tech/index.php
    [REMOTE_PORT] => 51803
    [REDIRECT_URL] => /index.php
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => 
    [REQUEST_URI] => /
    [SCRIPT_NAME] => /index.php
    [ORIG_SCRIPT_FILENAME] => /var/www/php-bin-isp-php70/pagekit/php
    [ORIG_PATH_INFO] => /index.php
    [ORIG_PATH_TRANSLATED] => /var/www/pagekit/data/www/pagekit.tech/index.php
    [ORIG_SCRIPT_NAME] => /php-bin/php
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1489409885.2106
    [REQUEST_TIME] => 1489409885
)

**Comment by Dennis14e** [comment]
I have the same problem. This pull request fixes it.
Debian 8.9 Jessie
Apache 2.4.10
PHP 5.6.30

**Comment by tobbexiv** [comment]
@Dennis14e as long as this pull is not merged, you can use my extension to enforce the rewriting: https://pagekit.com/marketplace/package/tobbe/enforce-modrewrite

However, you need to ensure that you can use the rewritten urls before installing the extension!

**Pull request merged**
